services:
  app: 
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile 
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
    container_name: library-front-dev
    environment:
      - VITE_URL=http://localhost:8080/api
      - VITE_WS_URL=ws://localhost:8080/api
  server:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    container_name: library-back
    environment:
      MONGODB_URI: ${MONGODB_URI}
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app 
  